// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_API_1.Models;

#nullable disable

namespace Test_API_1.Migrations
{
    [DbContext(typeof(MetalContext))]
    partial class MetalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Test_API_1.Models.Band", b =>
                {
                    b.Property<int>("BandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StyleID")
                        .HasColumnType("int");

                    b.HasKey("BandID");

                    b.HasIndex("StyleID");

                    b.ToTable("Bands");
                });

            modelBuilder.Entity("Test_API_1.Models.Style", b =>
                {
                    b.Property<int>("StyleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StyleID");

                    b.ToTable("Style");
                });

            modelBuilder.Entity("Test_API_1.Models.Band", b =>
                {
                    b.HasOne("Test_API_1.Models.Style", "Style")
                        .WithMany()
                        .HasForeignKey("StyleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Style");
                });
#pragma warning restore 612, 618
        }
    }
}
